apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
  namespace: users-api
  labels:
    app: users-api
data:
  AllowedHosts: "*"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5055"
  ApplicationInsightsAgent_EXTENSION_VERSION: "~3"
  Jwt__Issuer: "CloudGamesAPI"
  Jwt__Audience: "CloudGamesAPIClient"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  Serilog__Enrich__0: "FromLogContext"
  Serilog__MinimumLevel__Default: "Information"
  Serilog__MinimumLevel__Override__Microsoft: "Warning"
  Serilog__MinimumLevel__Override__System: "Warning"
  Serilog__WriteTo__0__Name: "Console"
  Redis__Host: "redis.users-api.svc.cluster.local"
  Redis__Port: "6379"
  MongoDB__ConnectionString: "mongodb://root:changeme123!@mongodb-0.mongodb.users-api.svc.cluster.local:27017/userdb?authSource=admin"
  MongoDB__DatabaseName: "userdb"
  Elasticsearch__Hosts: "http://elasticsearch.users-api.svc.cluster.local:9200"
  ServiceBus__QueueNameUserCreated: "UserCreatedEvent"
  Logging__LogLevel__Default: "Information"
