apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
  labels:
    app: users-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_HTTP_PORTS: "5055"
  Jwt__Issuer: "CloudGamesAPI"
  Jwt__Audience: "CloudGamesAPIClient"
  RabbitMq__HostName: "cloudgames-rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__ExchangeName: "cloudgames.topic"
  RabbitMq__QueueNameOrderPlaced: "OrderPlacedEvent"
  RabbitMq__QueueNamePaymentProcessed: "PaymentProcessedEvent"
