apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-api
  namespace: users-api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - users-api.example.com
    secretName: users-api-tls
  rules:
  - host: users-api.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: users-api
            port:
              number: 5055
