apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: users-api-keyvault
  namespace: users-api
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "0052f425-5ecb-40da-acec-30d48c0f8cba"
    keyvaultName: "kvcloudgamesfiap"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: ConnectionStrings--SqlConnection
          objectType: secret
          objectAlias: ConnectionStrings--SqlConnection
        - |
          objectName: Jwt--Key
          objectType: secret
          objectAlias: Jwt--Key
        - |
          objectName: Secrets--Password
          objectType: secret
          objectAlias: Secrets--Password
        - |
          objectName: ServiceBus--ConnectionString
          objectType: secret
          objectAlias: ServiceBus--ConnectionString
        - |
          objectName: ApplicationInsights--ConnectionString
          objectType: secret
          objectAlias: ApplicationInsights--ConnectionString
    tenantId: "e9130a74-a0a4-44d4-b597-7b8952f79f2c"
  secretObjects:
  - secretName: users-api-keyvault-secrets
    type: Opaque
    data:
      - key: ConnectionStrings__SqlConnection
        objectName: ConnectionStrings--SqlConnection
      - key: Jwt__Key
        objectName: Jwt--Key
      - key: Secrets__Password
        objectName: Secrets--Password
      - key: ServiceBus__ConnectionString
        objectName: ServiceBus--ConnectionString
      - key: ApplicationInsights__ConnectionString
        objectName: ApplicationInsights--ConnectionString
      - key: APPLICATIONINSIGHTS_CONNECTION_STRING
        objectName: ApplicationInsights--ConnectionString
