apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=dbUser;User Id=usuario_app;Password=SenhaForte123!;TrustServerCertificate=True;"
  ConnectionStrings__SetupConnection: "Server=sqlserver,1433;Database=dbUser;User Id=sa;Password=SenhaForte123!;TrustServerCertificate=True;"
  Jwt__Key: "chave-secreta-super-forte-123456"
  Secrets__Password: "TqgX6tPq1f5jLw9bC3yZk2uR8hV0nE6sQ4mD7pJ1cFo="
  RabbitMq__Password: "guest"
