apiVersion: v1
kind: Secret
metadata:
  name: users-api-keyvault-secrets
  namespace: users-api
type: Opaque
stringData:
  ConnectionStrings__SqlConnection: "Server=tcp:sql-posarqfiap2026.database.windows.net,1433;Initial Catalog=userdb;Persist Security Info=False;User ID=sqladminuser;Password=@tonytonardo2026;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  Jwt__Key: "chave-secreta-super-forte-123456"
  Secrets__Password: "TqgX6tPq1f5jLw9bC3yZk2uR8hV0nE6sQ4mD7pJ1cFo="
  ServiceBus__ConnectionString: "Endpoint=sb://sb-posarqfiap2026.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=3Xe7EV4z8jIsgAUJHzV/PvN4hdxdzjQkr+ASbIcFW7M="
  ApplicationInsights__ConnectionString: "InstrumentationKey=f8140186-1126-4f7f-ad23-c75190193f76;IngestionEndpoint=https://francecentral-1.in.applicationinsights.azure.com/;LiveEndpoint=https://francecentral.livediagnostics.monitor.azure.com/;ApplicationId=d4026e6d-73b1-49c0-ac67-d35f8e95cd59"
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=f8140186-1126-4f7f-ad23-c75190193f76;IngestionEndpoint=https://francecentral-1.in.applicationinsights.azure.com/;LiveEndpoint=https://francecentral.livediagnostics.monitor.azure.com/;ApplicationId=d4026e6d-73b1-49c0-ac67-d35f8e95cd59"
  RabbitMq__Password: "guest"
